org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_name=HyMod
mod_id=hymod
mod_version=1.0.0
mod_description=Multiversion mod for Hypixel and Ranked Bedwars adding features for bedwars (resource display), arcade, chat waypoints and more!
mod_archives_name=HyMod
base_group=tomeko.hymod

java_version=[VERSIONED]
minecraft_version=[VERSIONED]

fabric_loader_version=0.19.3
fabric_api_version=[VERSIONED]
fabric_language_kotlin_version=1.13.12+kotlin.2.4.0

oneconfig_version=1.0.0-beta.4
mod_menu_version=[VERSIONED]
hypixel_mod_api_version=[VERSIONED]

stonecutter_version=0.9.5