org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_name=HyMod
mod_id=hymod
mod_version=1.0.0
mod_description=
mod_archives_name=HyMod
base_group=tomeko.hymod

java_version=[VERSIONED]
minecraft_version=[VERSIONED]

hypixel_mod_api_version=1.0.2

stonecutter_version=0.9.4